name: Runs OWASP ZAP full scans
on:
  workflow_dispatch:

jobs:
  oswasp-zap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - https://scan-websites.alpha.canada.ca/en
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: OSWASP ZAP - Vulnerability Scan
        uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98 # v0.4.0
        with:
          allow_issue_writing: false
          cmd_options: '-d -s -z "-config globalexcludeurl.url_list.url.regex=^.*/(support|contactus|contact|careers|carrieres)/?$"'
          target: ${{ matrix.domain }}
